services:
  website:
    image: ghcr.io/egidiocaprino/website:latest
    restart: always
    volumes:
      - ./.env.production:/app/.env.production:ro
    networks:
      - web

networks:
  web:
    external: true
